nginx:
    build: ./nginx/
    ports:
        - 8080:80
    links:
        - php_postgres
    volumes_from:
        - app

php_postgres:
    build : ./php
    expose:
        - 9000
    links:
        - postgres
    volumes_from:
        - app

app:
    image: php:7.0-fpm
    volumes:
        - ./www/html:/var/www/html
    command: "true"

postgres:
    image: postgres:latest
    volumes_from:
        - data_postgres
    environment:
        POSTGRES_PASSWORD : root
        POSTGRES_DB : project
        POSTGRES_USER : project

data_postgres:
    image: postgres:latest
    volumes:
        - /var/lib/postgresql/data
    command: "true"
        
