version: "2.1"

services:
    nginx:
        build: ./nginx/
        ports:
            - 8080:80
        volumes_from:
            - app
        depends_on:
            - php
        networks:
            - server

    php:
        build : ./php
        expose:
            - 9000
        volumes_from:
            - app
        depends_on:
            - mysql
        networks:
            - server
            - database

    app:
        image: php:7.0-fpm
        volumes:
            - "${PROJECT_ROOT}:/var/www/html"
        command: "true"
        networks:
            - server

    mysql:
        image: mysql:latest
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD : "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE : "${DB_NAME}"
            MYSQL_USER : "${DB_USERNAME}"
            MYSQL_PASSWORD : "${DB_PASSWORD}"
        networks:
            - database

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8081:80
        environment:
            PMA_HOST : mysql
        depends_on:
            - mysql
        networks:
            - database

volumes:
    data:

networks:
    database:
    server:
